site_name: CrystalExpress Documentation - iOS
theme: readthedocs
site_favicon: favicon.ico
pages:
- Home: index.md
- Integration guide:
  - 'Pre-Stage': 'docs/pre-stage.md'
  - 'Getting Started': 'docs/getting-started.md'
- '中文': 'docs/pre-stage.md'
