site_name: CrystalExpress Documentation - iOS
theme: readthedocs
site_favicon: favicon.ico
extra_css:
- css/custom.css
pages:
- Home: index.md
- Integration guide:
  - 'Setup and Requirements': 'docs/setup.md'
  - 'AD integration':
    - 'Initialization': 'docs/sdk-init.md'
    - 'Splash AD': 'docs/splash-ad.md'
    - 'Stream AD': 'docs/stream-ad.md'
    - 'Content AD': 'docs/content-ad.md'
  - 'SDK integration':
    - 'Register background task': 'docs/register-background-task.md'
    - 'Register background fetch': 'docs/register-background-fetch.md'
    - 'AD preview': 'docs/ad-preview.md'
- Common placements:
  - 'Open Splash': 'docs/open-splash-ad.md'
  - 'Interstitial Splash': 'docs/interstitial-ad.md'
- Sample code: 'docs/sample-code.md'
- Trouble shooting: 'docs/trouble-shooting.md'
- API reference: 'docs/api-reference.md'
